### ISSUE TITLE
main.yml playbook fails on first deploy

### ISSUE THREAD

**Issue by RobinSikkens** [svsticky/sadserver#185] opened 2018-10-25 20:27 UTC
When running the main.yml playbook the playbook fails on the task:
 `run pretix migration if package version changed`

This is problably due to a missing dependency.

**Comment by tomwassenberg** [comment] 2018-10-27 14:59
I can't reproduce this on the current `master` (d682c1a) 😕 

However, when running the task commands manually I do get the following warnings, which maybe need addressing (@maartenberg?):
```
pretix@dev.svsticky.nl:~$ /var/www/pretix/venv/bin/python -m pretix migrate
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: auth, badges, banktransfer, contenttypes, otp_static, otp_totp, paypal, pretix_pages, pretixbase, pretixdroid, pretixhelpers, pretixmultidomain, sessions, stripe
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by tomwassenberg** [comment] 2019-01-22 18:34
I think we can attribute this to some issue in Pretix with a certain migration path. I haven't encountered this on staging recently, and I think it never occurred on production either. So closing this for now :)

**Closed by tomwassenberg** 2019-01-22 18:34 UTC
Labels: bug
